name: "ttc_analytics"
version: "1.0.0"
config-version: 2

profile: "ttc_analytics"

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

models:
  ttc_analytics:
    staging:
      +materialized: table
    intermediate:
      +materialized: table
    marts:
      +materialized: table
