version: 2

sources:
  - name: gtfs_raw
    schema: main
    tables:
      - name: routes
        description: "Raw static routes data from GTFS"
        config:
          external_location: "../backend/data/gtfs_raw/static_routes.csv"

      - name: trips
        description: "Raw static trips data from GTFS"
        config:
          external_location: "../backend/data/gtfs_raw/static_trips.csv"

      - name: stop_times
        description: "Raw static stop times data from GTFS"
        config:
          external_location: "../backend/data/gtfs_raw/static_stop_times.csv"

      - name: shapes
        description: "Raw static shapes data from GTFS"
        config:
          external_location: "../backend/data/gtfs_raw/static_shapes.csv"
        
      - name: stops
        description: "Raw static stops data from GTFS"
        config:
          external_location: "../backend/data/gtfs_raw/static_stops.csv"
